# Generated by Django 5.0.4 on 2024-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='foo',
        ),
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ManyToManyField(to='app.foo'),
        ),
    ]
