# Generated by Django 5.0.4 on 2024-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_skill_delete_bar_delete_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='sample desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(verbose_name='Is it remote?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='related_jobs',
            field=models.ManyToManyField(to='app.job', verbose_name='Related Jobs'),
        ),
    ]
