# Generated by Django 5.0.4 on 2024-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skill_description_skill_link_alter_job_is_remote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('related_skills', models.ManyToManyField(to='app.skill', verbose_name='Related Skills')),
            ],
        ),
    ]
